spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test_db
    username: testuser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#  r2dbc:
#    url: r2dbc:mariadb://localhost:3306/webflux
#    username: admin
#    password: